# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fbdc1bcd18d5eb863b90145fdc50aa56af2ea38bc8bd35d3e398f434f18f42aeaf754136f9f7fc0cc8061a0f639ff3778449fe38013f9456e965913842bce1b3

test:
  secret_key_base: c6a3bdabaf400d19924542d350bad66424ca59aa74026feb3acbbe9461cada52d1d579a56ab6d3de43e4d4b78dc7ae423db29b15d208354cc26151166ae50c59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
